name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: |
        echo ::set-env name=release::"${GITHUB_REF##*/}"

    - name: Initialise build environment
      run: yarn install

    - name: Build release for linux64
      run: yarn gulp release --linux64

    - name: Move artifacts
      run: mv release/heliflight-blackbox* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heliflight-blackbox-snapshot-linux-${{ env.release }}
        path: heliflight-blackbox*


  macos:

    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: |
        echo ::set-env name=release::"${GITHUB_REF##*/}"

    - name: Initialise build environment
      run: yarn install

    - name: Build release for MacOS
      run: yarn gulp release --osx64

    - name: Move artifacts
      run: mv release/heliflight-blackbox* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heliflight-blackbox-snapshot-macos-${{ env.release }}
        path: heliflight-blackbox*


  windows:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: |
        $snapshot = $env:GITHUB_REF -replace '.*/',''
        echo "::set-env name=release::$snapshot"

    - name: Initialise build environment
      run: yarn install

    - name: Build release for windows
      run: yarn gulp release --win32

    - name: Move artifacts
      run: move release/heliflight-blackbox* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heliflight-blackbox-snapshot-windows-${{ env.release }}
        path: heliflight-blackbox*

